<?php

########################################################################
# Extension Manager/Repository config file for ext: "solrpanel"
#
# Auto generated by Extension Builder 2012-07-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SolrPanel',
	'description' => 'Allows to analyze and compare results from solr to find the best configuration for your needs',
	'category' => 'plugin',
	'author' => 'Grigori Prokhorov',
	'author_email' => 'grigori.prokhorov@dkd.de',
	'author_company' => 'dkd Internet Service GmbH',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'solr' => '',
			'devlog' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>